name: Android CI (APK)

on:
  push:
    branches: ['**']
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept Licenses and Install components
        run: |
          sdkmanager --install 'platform-tools' 'platforms;android-34' 'build-tools;34.0.0'
          yes | sdkmanager --licenses

      # ✅ Plus de SDKMAN. On utilise l'action Gradle officielle.
      - name: Build Debug APK with Gradle 8.7
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: '8.7'
          arguments: 'assembleDebug --stacktrace --no-daemon'

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: miam-debug-apk
          path: app/build/outputs/apk/debug/*.apk
